In [7]:
import torch
import numpy as np
from pathlib import Path

In [8]:
root_dir = Path("../new-paradigm/new-10-client-1-server-10-ood-2-severe-untrained-Adam")
b = torch.load(root_dir/"cosine_dis_all_distribution_inchannelwise.pt")
# b = torch.load(root_dir/"mahal_dis_all_pca.pt")

In [9]:
b[8]

{'features.conv0.weight': {0: 0.9716838688162543,
  1: 0.9770605555321393,
  2: 0.9669134955178076,
  3: 0.9806241422043017,
  4: 0.9648581966426749,
  5: 0.9649884744669297,
  6: 0.9833318126886853,
  7: 0.9865690354521798},
 'features.norm0.weight': {0: 0.8734177718374483,
  1: 0.7692094030765456,
  2: 0.6675063972377284,
  3: 0.853681032088593,
  4: 0.8026799678114372,
  5: 0.7615997372372068,
  6: 0.9005999462612623,
  7: 0.9384226456433534},
 'features.norm0.bias': {0: 0.888476076841205,
  1: 0.7743958146445642,
  2: 0.6776835475290182,
  3: 0.8709249105862062,
  4: 0.8300492812347289,
  5: 0.8169049735923664,
  6: 0.9310201981714419,
  7: 0.9556657570637936},
 'features.norm0.running_mean': {},
 'features.norm0.running_var': {},
 'features.norm0.num_batches_tracked': {},
 'features.denseblock1.denselayer1.norm1.weight': {0: 0.8579964707834167,
  1: 0.6575855776357229,
  2: 0.7001695034674825,
  3: 0.8188833434008619,
  4: 0.6264908941083094,
  5: 0.6432421213692752,
  6: 0.931299

In [10]:
a[8]

NameError: name 'a' is not defined

In [ ]:
a[1]

{'features.conv0.weight': {0: 0.23080130642722488,
  1: 0.30105729192261615,
  2: 0.2013620769343134,
  3: 0.26355280783056584,
  4: 0.2326226936102678,
  5: 0.22968506622067744,
  6: 0.3705219211916424,
  7: 0.3853581901866043},
 'features.denseblock1.denselayer1.conv1.weight': {0: 0.0118790864944458,
  1: 0.008991003036499023,
  2: 0.02141392230987549,
  3: 0.012674331665039062,
  4: 0.006893038749694824,
  5: 0.013931989669799805,
  6: 0.01111459732055664,
  7: 0.010631203651428223},
 'features.denseblock1.denselayer1.conv2.weight': {0: 0.07214704262286153,
  1: 0.09252720912251305,
  2: 0.09414428133046436,
  3: 0.10450194069908625,
  4: 0.08298731686487013,
  5: 0.08674559614569466,
  6: 0.16096665321458087,
  7: 0.14345062480469492},
 'features.denseblock1.denselayer2.conv1.weight': {0: 0.012961784998575846,
  1: 0.011852264404296875,
  2: 0.010413249333699545,
  3: 0.00604557991027832,
  4: 0.006483713785807292,
  5: 0.011167367299397787,
  6: 0.009765942891438803,
  7: 0.015185

In [ ]:
l = 0
for (key, value) in b[1].items():
    if "conv" in key:
        l += 1
        print(a[1][key])
        print(b[1][key])
        print()
    
    if l > 20:
        break
    

{0: 5.386093422731055, 1: 5.358810601327906, 2: 5.805700414758571, 3: 5.685960068100496, 4: 5.546270296840139, 5: 5.726576235452316, 6: 5.6352430572823335, 7: 2.764129596877579}
{0: 5.386093422731105, 1: 5.3588106013279315, 2: 5.805700414758604, 3: 5.685960068100528, 4: 5.546270296840156, 5: 5.726576235452337, 6: 5.635243057282415, 7: 2.764129596877606}

{0: 0.6985696556534556, 1: 0.656876793868537, 2: 0.6916282952672919, 3: 0.7380510927020292, 4: 0.718344545020094, 5: 0.6489578667209922, 6: 0.5811042364735717, 7: 0.4760950319792153}
{0: 0.6985696556534556, 1: 0.656876793868537, 2: 0.6916282952672921, 3: 0.7380510927020292, 4: 0.7183445450200939, 5: 0.6489578667209922, 6: 0.5811042364735715, 7: 0.47609503197921527}

{0: 2.154225872801644, 1: 1.8880746534693083, 2: 2.6264231131264637, 3: 2.2267678404527143, 4: 2.391020028584731, 5: 2.62531132009774, 6: 1.988271585569064, 7: 1.0961680541938188}
{0: 2.154225872801666, 1: 1.88807465346933, 2: 2.6264231131265072, 3: 2.2267678404527396, 4: 2

## Cosine Debugging

In [ ]:
epoch = 8
client_models = [torch.load(client_paths[i]/f"epoch-{epoch}.pt", map_location='cpu') for i in range(len(client_paths))]            
prev_server_model = torch.load(server_path/f"epoch-{epoch-1}.pt", map_location='cpu')
keys = list(prev_server_model.keys())


In [ ]:
key = ""
sad = 0
for i in keys:
    if "conv" in i:
        sad += 1
        if sad == 3:
            key = i
            break


In [ ]:
fin_cosine = {}
cosine_dis = {}
cosine_dis[key] = {}


for i in range(len(client_models)):
    client_models[i][key] = client_models[i][key] - prev_server_model[key]

temp_m = {}
used_channels = 0
for in_channel in range(client_models[0][key].shape[1]):
    try:
        train_data, test_data = [], []

        num_samples_per_client = client_models[0][key].shape[0]

        for i in distribution_clients:
            train_data.extend(client_models[i][key][:,in_channel].unsqueeze(dim=1).numpy())

        for i in test_clients:
            test_data.extend(client_models[i][key][:,in_channel].unsqueeze(dim=1).numpy())
            
                
        train_data = np.array(train_data).astype(np.float64)
        test_data = np.array(test_data).astype(np.float64)
        

        
        train_data = train_data.reshape(train_data.shape[0], -1)
        test_data = test_data.reshape(test_data.shape[0], -1)
        # print(train_data.shape, end = " ")
        m = CosineSimilarity(device1, device2)

        train_data, test_data = torch.tensor(train_data), torch.tensor(test_data)
        cosineDis = m.cosineSimilarity(test_data, train_data)
        cosineDis = cosineDis.sum(dim = 1)/cosineDis.shape[1]

        for i in range(len(test_clients)):
            client = test_clients[i]
            if i in temp_m.keys():
                # print(key)
                temp_m[client] += torch.sum(cosineDis[i*num_samples_per_client: (i+1)*num_samples_per_client]).item()/num_samples_per_client
            else:
                temp_m[client] = torch.sum(cosineDis[i*num_samples_per_client: (i+1)*num_samples_per_client]).item()/num_samples_per_client
        
        used_channels += 1
    except:
        # print(key, in_channel)
        continue
    # break

# print(used_channels, client_models[0][key].shape[1])

for (i, j) in temp_m.items():
    cosine_dis[key][i] = j/used_channels

fin_cosine[epoch] = cosine_dis
# break

In [ ]:
fin_cosine = {}
cosine_dis = {}
cosine_dis[key] = {}
in_channel = 0


train_data, test_data = [], []

num_samples_per_client = client_models[0][key].shape[0]

for i in distribution_clients:
    train_data.extend(client_models[i][key][:,in_channel].unsqueeze(dim=1).numpy())

for i in test_clients:
    test_data.extend(client_models[i][key][:,in_channel].unsqueeze(dim=1).numpy())
    
        
train_data = np.array(train_data).astype(np.float64)
test_data = np.array(test_data).astype(np.float64)



train_data = train_data.reshape(train_data.shape[0], -1)
test_data = test_data.reshape(test_data.shape[0], -1)
# print(train_data.shape, end = " ")


In [ ]:
m = CosineSimilarity(device1, device2)

train_data, test_data = torch.tensor(train_data), torch.tensor(test_data)
cosineDis = m.cosineSimilarity(test_data, train_data)


/tmp/ipykernel_3991923/1221605967.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_data, test_data = torch.tensor(train_data), torch.tensor(test_data)


In [ ]:
used_channels = 0
cosineDis = cosineDis.sum(dim = 1)/cosineDis.shape[1]

In [ ]:
temp_m = {}
for i in range(len(test_clients)):
    client = test_clients[i]
    if i in temp_m.keys():
        # print(key)
        temp_m[client] += torch.sum(cosineDis[i*num_samples_per_client: (i+1)*num_samples_per_client]).item()/num_samples_per_client
    else:
        temp_m[client] = torch.sum(cosineDis[i*num_samples_per_client: (i+1)*num_samples_per_client]).item()/num_samples_per_client

used_channels += 1
    # except:
    #     # print(key, in_channel)
    #     continue
    # break

# print(used_channels, client_models[0][key].shape[1])

for (i, j) in temp_m.items():
    cosine_dis[key][i] = j/used_channels

fin_cosine[epoch] = cosine_dis
# break

In [ ]:
alpha, beta = [], []

In [ ]:
import torch
import torchvision
import os
import numpy as np
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from tqdm.auto import tqdm


root_dir = "../new-paradigm/new-10-client-1-server-10-ood-2-severe-untrained-Adam/models"
path = Path(root_dir)
client_paths = [path/f"client-{i}" for i in range(8)]
server_path = path/"server"
distribution_clients = [0,1,2,3,4,5,6,7]
test_clients = [0,1,2,3,4,5,6,7]
server_path = path/"server"
_,_,files = next(os.walk(client_paths[0]))
num_epochs = len(files)
device1 = "cuda:0" if torch.cuda.is_available() else 'cpu'
device2 = "cuda:0" if torch.cuda.is_available() else 'cpu'
# pca_percent_variation = 0.95


class CosineSimilarity:
    def __init__(self, device1, device2):
        self.device1 = device1
        self.device2 = device2

    def _cosineSimilarity(self, x, y):
        # print(cov.shape)
        x = x/torch.norm(x, dim = 1).reshape(-1, 1)
        y = y/torch.norm(y, dim = 1).reshape(-1, 1)
        return torch.mm(x, y.T)
    
    def cosineSimilarity(self, test_data, train_data):
        train_data = train_data.to(self.device1)
        test_data = test_data.to(self.device1)
        
        return 1-self._cosineSimilarity(test_data, train_data)
    
    
    def pca_transform(self, train_data, test_data, percent_variation):
        if torch.is_tensor(train_data):
            train_data = train_data.to('cpu').numpy()
        if torch.is_tensor(test_data):
            test_data = test_data.to('cpu').numpy()

        scalar = StandardScaler()
        scalar.fit(train_data)
        train_data = scalar.transform(train_data)
        test_data = scalar.transform(test_data)

        pca = PCA(percent_variation)
        pca.fit(train_data)
        train_data = pca.transform(train_data)
        test_data = pca.transform(test_data)

        train_data = torch.tensor(train_data).to(self.device1)
        test_data = torch.tensor(test_data).to(self.device2)

        return train_data, test_data, pca


In [ ]:
alpha = []
used_channels = 0
temp_m = {}
epoch = 8
fin_cosine = {}
cosine_dis = {}
cosine_dis[key] = {}
in_channel = 0

epoch = 8
client_models = [torch.load(client_paths[0]/f"epoch-{epoch}.pt", map_location='cpu') for i in range(len(client_paths))]            
prev_server_model = torch.load(server_path/f"epoch-{epoch-1}.pt", map_location='cpu')
keys = list(prev_server_model.keys())



# for i in range(len(client_models)):
#     client_models[i][key] = client_models[i][key] - prev_server_model[key]

per_client = [0 for _ in test_clients]

for in_channel in range(client_models[0][key].shape[1]):
    try:
        train_data, test_data = [], []
        # total = 0

        num_samples_per_client = []
        # num_samples_per_client = client_models[0][key].shape[0]

        for i in distribution_clients:
            tmp = client_models[i][key][:,in_channel].reshape(client_models[i][key][:,in_channel].shape[0], -1).numpy()
            # alpha.append(tmp[(tmp==0).all(1)])
            tmp = tmp[~(tmp==0).all(1)]
            # f[~(f==0).all(1)]
            train_data.extend(tmp)

        for i in test_clients:
            tmp = client_models[i][key][:,in_channel].reshape(client_models[i][key][:,in_channel].shape[0], -1).numpy()
            tmp = tmp[~(tmp==0).all(1)]
            num_samples_per_client.append(tmp.shape[0])
            per_client[i] += tmp.shape[0]
            test_data.extend(tmp)
            
                
        train_data = np.array(train_data).astype(np.float64)
        test_data = np.array(test_data).astype(np.float64)

        
        # per_channel.append(np.array(num_samples_per_client).sum())
        train_data = train_data.reshape(train_data.shape[0], -1)
        test_data = test_data.reshape(test_data.shape[0], -1)
        # print(train_data.shape, end = " ")
        m = CosineSimilarity(device1, device2)

        train_data, test_data = torch.tensor(train_data), torch.tensor(test_data)
        cosineDis = m.cosineSimilarity(test_data, train_data)
        alpha.append(cosineDis)
        cosineDis[torch.isnan(cosineDis)] = 0
        # beta.append(cosineDis)
        cosineDis = cosineDis.sum(dim = 1)/cosineDis.shape[1]
        
        tmp = 0
        for i in range(len(test_clients)):
            client = test_clients[i]
            if i in temp_m.keys():
                # print(key)
                temp_m[client] += torch.sum(cosineDis[tmp: tmp + num_samples_per_client[i]]).item()
            else:
                temp_m[client] = torch.sum(cosineDis[tmp: tmp + num_samples_per_client[i]]).item()
            tmp += num_samples_per_client[i]
        
        used_channels += 1
    except:
        # print(key, in_channel)
        continue
    # break

# print(used_channels, client_models[0][key].shape[1])
tmp = np.array(per_client).sum()
for (i, j) in temp_m.items():
    cosine_dis[key][i] = j

In [ ]:
num_samples_per_client

[32, 32, 32, 32, 32, 32, 32, 32]

In [ ]:
alpha[0]

tensor([[ 1.1102e-16,  4.0884e-01,  3.8597e-01,  ...,  1.0590e+00,
          5.5019e-01,  1.4736e+00],
        [ 4.0884e-01, -4.4409e-16,  2.4506e-01,  ...,  1.5914e+00,
          3.3405e-01,  1.9314e+00],
        [ 3.8597e-01,  2.4506e-01, -2.2204e-16,  ...,  1.5390e+00,
          8.6541e-02,  1.7317e+00],
        ...,
        [ 1.0590e+00,  1.5914e+00,  1.5390e+00,  ...,  2.2204e-16,
          1.7006e+00,  3.6133e-01],
        [ 5.5019e-01,  3.3405e-01,  8.6541e-02,  ...,  1.7006e+00,
          1.1102e-16,  1.6744e+00],
        [ 1.4736e+00,  1.9314e+00,  1.7317e+00,  ...,  3.6133e-01,
          1.6744e+00,  0.0000e+00]], device='cuda:0', dtype=torch.float64)

In [ ]:
cosine_dis2

{'features.denseblock1.denselayer1.conv2.weight': {0: 0.04168869638415004,
  1: 0.07172623997789287,
  2: 0.07103704246095495,
  3: 0.07115868325654974,
  4: 0.06912007511298307,
  5: 0.08336353234281954,
  6: -0.0041175435027075965,
  7: 0.011930821807951875}}

In [ ]:
cosine_dis

{'features.denseblock1.denselayer1.conv2.weight': {0: 3664.8455175509207,
  1: 3664.8455175509207,
  2: 3664.8455175509207,
  3: 3664.8455175509207,
  4: 3664.8455175509207,
  5: 3664.8455175509207,
  6: 3664.8455175509207,
  7: 3664.8455175509207}}

1152

In [ ]:
for (key, value) in cosine_dis.items():
    for (k, v) in value.items():
        print(cosine_dis[key][k] + cosine_dis2[key][k])

0.9999999999999998
1.0
1.0
0.9999999999999999
0.9999999999999996
0.9999999999999998
1.0
1.0000000000000002


In [ ]:
cosine_dis

{'features.denseblock1.denselayer1.conv2.weight': {0: 0.9815789412861118,
  1: 0.943879490824279,
  2: 0.9457086938989069,
  3: 0.9443165430408196,
  4: 0.9462007378150229,
  5: 0.9326731115963441,
  6: 1.0120205556153794,
  7: 0.9881421027233428}}

In [ ]:
alpha[8].sum(dim=1)/alpha[8].shape[1]

tensor([0.9930, 1.0466, 0.9318, 0.9943, 1.0368, 0.9910, 0.9640, 0.9765, 0.9941,
        0.9950, 0.9943, 0.9989, 0.9943, 0.9807, 1.0275, 0.9852, 0.9981, 0.9529,
        0.9901, 0.9982, 0.9753, 0.9819, 1.0015, 0.9914, 0.9135, 0.9514, 1.0008,
        1.0774, 0.9292, 0.9346, 0.9492, 0.9579, 0.9265, 0.9880, 1.0617, 0.9471,
        0.9524, 1.0053, 1.0050, 0.9317, 0.9760, 1.0467, 0.9912, 0.9416, 0.9605,
        0.9658, 1.0156, 0.9802, 0.9463, 1.0028, 0.9399, 0.9661, 1.0206, 0.9740,
        0.9426, 0.9371, 1.0104, 0.9671, 0.9849, 0.9797, 0.9837, 0.9738, 0.9864,
        0.9985, 0.9799, 1.0408, 0.9896, 1.0127, 0.9792, 0.9913, 0.9784, 0.9828,
        0.9693, 0.9800, 0.9902, 1.0011, 0.9852, 0.9929, 1.0437, 1.0086, 0.9988,
        0.9960, 0.9239, 1.0432, 0.9805, 0.9621, 0.9465, 1.0418, 1.0473, 0.9985,
        0.9928, 0.9941, 0.9746, 0.9880, 1.0283, 0.9595, 0.9885, 0.9224, 1.0342,
        1.0129, 0.9378, 1.0260, 0.9807, 1.0248, 0.9729, 0.9559, 0.9797, 1.0207,
        0.9798, 0.9792, 0.9831, 0.9785, 

In [ ]:
alpha[0] == 0

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
alpha[8].sum(dim=1)/alpha[8].shape[1] + beta[8].sum(dim=1)/beta[8].shape[1]

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 

In [ ]:
alpha[8][0].sum()/256

tensor(0.0044, device='cuda:0', dtype=torch.float64)

In [ ]:
beta[8][0]

tensor([2.2204e-16, 6.8779e-01, 4.1610e-01, 1.8759e+00, 1.2115e+00, 1.8672e+00,
        0.0000e+00, 1.7701e-01, 1.8068e+00, 1.7205e+00, 0.0000e+00, 0.0000e+00,
        1.5096e+00, 1.6898e+00, 1.8601e+00, 0.0000e+00, 1.5232e+00, 1.1278e-01,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 6.6962e-01, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 1.7006e+00, 0.0000e+00, 0.0000e+00, 1.8819e+00, 1.6598e+00,
        5.7210e-02, 1.2500e+00, 1.8895e+00, 1.6533e+00, 1.9231e+00, 2.1900e-01,
        1.4869e+00, 1.7926e+00, 0.0000e+00, 1.9327e+00, 1.6960e+00, 1.6938e+00,
        0.0000e+00, 0.0000e+00, 1.0998e+00, 1.7839e+00, 1.8370e+00, 0.0000e+00,
        7.3288e-01, 1.9290e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 4.2931e-01,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 1.8157e+00, 0.0000e+00, 0.0000e+00,
        1.7802e+00, 8.5407e-01, 1.8983e+00, 4.3274e-01, 1.9080e+00, 3.8773e-01,
        1.9109e+00, 1.2817e+00, 3.8897e-01, 1.9005e+00, 0.0000e+00, 1.3284e+00,
        1.8770e+00, 7.4707e-01, 0.0000e+

In [ ]:
cosine_dis

{'features.denseblock1.denselayer1.conv2.weight': {0: 0.015924507422461973,
  1: 0.027471427772135248,
  2: 0.027986657500969042,
  3: 0.027092213268041534,
  4: 0.02654726889363878,
  5: 0.03405196330025024,
  6: -0.0016552058441093268,
  7: 0.004498757859693424}}

In [ ]:
f = []
for i in range(alpha[-1].shape[0]):
    for j in range(alpha[-1].shape[0]):
        if torch.isnan(alpha[-1][i][j]):
            f.append((i,j))

In [ ]:
1 - train_data[38]/torch.norm(train_data[38])

tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan], dtype=torch.float64)

In [ ]:
alpha[-1][torch.isnan(alpha[-1])] = 0

In [ ]:
alpha[-1][torch.isnan(alpha[-1])]

tensor([], device='cuda:0', dtype=torch.float64)

In [ ]:
import numpy as np
f = np.array([[0,0,1], [0,0,0]], dtype = np.float64)

In [ ]:
f[~(f==0).all(1)]

array([[0., 0., 1.]])

In [ ]:
l = torch.load(path/"../cosine_dis_all_distribution_inchannelwise.pt")

In [ ]:
cosine_dis

{'features.denseblock1.denselayer1.conv2.weight': {0: 0.9583113036158497,
  1: 0.9282737600221072,
  2: 0.928962957539045,
  3: 0.9288413167434502,
  4: 0.9308799248870165,
  5: 0.9166364676571802,
  6: 1.0041175435027077,
  7: 0.9880691781920483}}

In [ ]:
l[epoch][key]

{0: 0.9583113036158497,
 1: 0.9282737600221072,
 2: 0.928962957539045,
 3: 0.9288413167434502,
 4: 0.9308799248870165,
 5: 0.9166364676571802,
 6: 1.0041175435027077,
 7: 0.9880691781920483}

In [ ]:
key

'features.denseblock1.denselayer1.conv2.weight'

In [ ]:
l[2].keys()

NameError: name 'l' is not defined

In [ ]:
l[2]

{1: {'features.conv0.weight': {0: 0.7687470276110778,
   1: 0.698353554864228,
   2: 0.7982438681206095,
   3: 0.7359314332500005,
   4: 0.7632224264833579,
   5: 0.7698654522407301,
   6: 0.6287529869860647,
   7: 0.6138876841965922},
  'features.norm0.weight': {0: 0.43259723974472786,
   1: 0.5912380097139938,
   2: 0.39344258721008385,
   3: 0.4708896633298508,
   4: 0.36911953778230044,
   5: 0.4480491654377754,
   6: 0.610349811736687,
   7: 0.6624172643529628},
  'features.norm0.bias': {0: 0.4417721154638271,
   1: 0.548451580033364,
   2: 0.4213012318371099,
   3: 0.460537246900118,
   4: 0.3921482285489444,
   5: 0.5190976414801678,
   6: 0.5615430760401073,
   7: 0.6008110231507029},
  'features.norm0.running_mean': {},
  'features.norm0.running_var': {},
  'features.norm0.num_batches_tracked': {},
  'features.denseblock1.denselayer1.norm1.weight': {0: 0.6500030984103233,
   1: 0.6186563659398334,
   2: 0.4706178586094789,
   3: 0.48666875788734015,
   4: 0.47780036179817176,


In [ ]:
import torch
from pathlib import Path
sd = torch.load(Path("../new-paradigm/new-10-client-1-server-10-ana-50-untrained-Adam/models/../mahal_dis_all_pca.pt"))
sd2 = torch.load(Path("../new-paradigm/new-10-client-1-server-10-ana-50-untrained-Adam/models/../euclidean_dis_fin.pt"))

In [ ]:
sd2[3]['features.denseblock4.denselayer13.norm1.running_mean']

{0: 2.039058203365353,
 1: 2.039058203365353,
 2: 2.039058203365353,
 3: 2.039058203365353,
 4: 2.039058203365353,
 5: 2.039058203365353,
 6: 7.468369157040961,
 7: 7.623815768187235}

In [ ]:
sd[3]['features.denseblock4.denselayer13.norm1.running_mean']

{0: 0.9277383794305356,
 1: 0.9277383794305356,
 2: 0.9277383794305356,
 3: 0.9277383794305356,
 4: 0.9277383794305356,
 5: 0.9277383794305356,
 6: 4.739425276085664,
 7: 5.326692880990038}

In [ ]:
root_dir = "../new-paradigm/new-10-client-1-server-10-sfa-untrained-Adam/models"
path = Path(root_dir)
epoch = 3

client_paths = [path/f"client-{i}" for i in range(8)]
server_path = path/"server"

client_models = [torch.load(client_paths[i]/f"epoch-{epoch}.pt", map_location='cpu') for i in range(len(client_paths))]            
prev_server_model = torch.load(server_path/f"epoch-{epoch-1}.pt", map_location='cpu')
keys = list(prev_server_model.keys())

In [ ]:
for (key, value) in prev_server_model.items():
    for i in range(len(client_models)):
        client_models[i][key] = client_models[i][key] - value

In [ ]:
for i in client_models:
    print(i['features.denseblock4.denselayer16.conv2.weight'])

tensor([[[[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         ...,

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]]],


        [[[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         ...,

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         [[nan, nan, nan],
          [nan, nan, nan],
          [nan, nan, nan]],

         [[nan, nan, nan],
          [nan, nan, nan],
 

In [ ]:
import torch
from pathlib import Path

dirs = [
    "../new-paradigm/new-10-client-1-server-10-ood-2-severe-untrained-Adam/models",
    "../new-paradigm/new-10-client-1-server-10-ana-10-untrained-Adam/models",
    # "../new-paradigm/new-10-client-1-server-10-ana-25-untrained-Adam/models",
    "../new-paradigm/new-10-client-1-server-10-ana-50-untrained-Adam/models",
    "../new-paradigm/new-10-client-1-server-10-ana-75-untrained-Adam/models",
    "../new-paradigm/new-10-client-1-server-10-sfa-untrained-Adam/models"
]


In [17]:
root_dir = Path(dirs[3])
cmp = torch.load(root_dir/"../comparison.pt", map_location = 'cpu')
mahal = torch.load(root_dir/"../mahal_dis_all_pca.pt")
euclid = torch.load(root_dir/"../euclidean_dis_fin.pt")

In [18]:
cmp[6]['mahal/euclid']

{'features.conv0.weight': {0: 13.39364520414123,
  1: 12.722141301260233,
  2: 14.18099524781051,
  3: 10.994559761335585,
  4: 13.315290786371257,
  5: 14.198594372342983,
  6: 45.39553828094841,
  7: 46.24366259102918},
 'features.norm0.weight': {0: 1.4988773616157465,
  1: 1.726936505385317,
  2: 1.487199381834798,
  3: 1.4943738221293261,
  4: 1.4995395476145934,
  5: 1.4948853006626703,
  6: 0.5313766798711436,
  7: 0.42709230859968184},
 'features.norm0.bias': {0: 32.20962219994572,
  1: 37.368865845017034,
  2: 29.58507867395484,
  3: 32.49903461036936,
  4: 35.79666022964292,
  5: 34.65914171101656,
  6: 25.264247358078713,
  7: 18.213655039253315},
 'features.norm0.running_mean': {0: 1.0772575448791537,
  1: 1.0772575448791537,
  2: 1.0772575448791537,
  3: 1.0772575448791537,
  4: 1.0772575448791537,
  5: 1.0772575448791537,
  6: 2.6276394699005583,
  7: 1.6473454073354883},
 'features.norm0.running_var': {0: 4.958981603485612,
  1: 4.958981603485612,
  2: 4.958981603485612,


In [ ]:
mahal[5]['mahal/']

{'features.conv0.weight': {0: 1.9074310291996686,
  1: 1.6273150866874664,
  2: 1.5871266518831462,
  3: 1.4366878134755037,
  4: 1.520558796653507,
  5: 1.4535504694718417,
  6: 13.238816254606514,
  7: 13.228997115532621},
 'features.norm0.weight': {0: 2.4754331030179126,
  1: 2.4756504925583567,
  2: 2.496645862162357,
  3: 2.5646140025744693,
  4: 2.9176392196121412,
  5: 2.475325942364931,
  6: 2.97131411419203,
  7: 2.7320935829441617},
 'features.norm0.bias': {0: 2.553530611922553,
  1: 2.566918450624839,
  2: 2.4752629974764138,
  3: 2.4906094998370576,
  4: 2.4820120432394774,
  5: 2.5230561086502195,
  6: 3.0871431075706393,
  7: 2.9161104261769295},
 'features.norm0.running_mean': {0: 0.8274403482346213,
  1: 0.8274403482346213,
  2: 0.8274403482346213,
  3: 0.8274403482346213,
  4: 0.8274403482346213,
  5: 0.8274403482346213,
  6: 4.096213615511077,
  7: 5.9256298261688505},
 'features.norm0.running_var': {0: 0.7366285570741081,
  1: 0.7366285570741081,
  2: 0.7366285570741

In [ ]:
euclid[5]

{'features.conv0.weight': {0: 0.0784126584018967,
  1: 0.07360804729065656,
  2: 0.07384542400159336,
  3: 0.07267260320462784,
  4: 0.07248088310462052,
  5: 0.07135353124696459,
  6: 0.19116401533275726,
  7: 0.19059958095087706},
 'features.norm0.weight': {0: 1.1747153266871535,
  1: 1.1557761192776792,
  2: 1.1681220928503075,
  3: 1.1599637366577376,
  4: 1.154296844621909,
  5: 1.1586817914445111,
  6: 4.293816722759549,
  7: 4.010177072318738},
 'features.norm0.bias': {0: 0.07350816618279322,
  1: 0.05920308138051997,
  2: 0.07263796032879055,
  3: 0.06425313841462409,
  4: 0.058418010501133114,
  5: 0.06286697588583952,
  6: 0.1054029832108773,
  7: 0.0918163386713141},
 'features.norm0.running_mean': {0: 0.387641134262405,
  1: 0.387641134262405,
  2: 0.387641134262405,
  3: 0.387641134262405,
  4: 0.387641134262405,
  5: 0.387641134262405,
  6: 1.3973192664649965,
  7: 1.4143293258462935},
 'features.norm0.running_var': {0: 0.09683942590359966,
  1: 0.09683942590359966,
  2: 